eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://192.168.2.85:9200
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1
  collector:
    rabbitmq:
#        addresses: 192.168.2.201:5672
      concurrency: 1
      connection-timeout: 60000
#        password: admin
#        username: admin
      queue: zipkin
      uri: amqp://admin:admin@192.168.2.201:5672/epm-monitor-service
#        virtual-host: epm-monitor-service