server:
  port: 8888
spring:
  application:
    name: zuul
  zipkin:
#    base-url: http://localhost:9000
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #virtual-host: epm-monitor-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    producer:
      path: /producer/**
      service-id: PRODUCER